spring:
  profiles:
    active: local
  data:
      elasticsearch:
        cluster-name: elasticsearch
        cluster-nodes: localhost:9300
        repositories:
          enabled: true

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
    org.hibernate: INFO

kafka:
  bootstrap-servers: localhost:9092
  group:
    groupId: test
  topic:
    deviation: deviation_topic
    distress: distress_topic
    video: video_topic
    routeintiation: route_intiation
    endtrip: end_trip
    sharelocation: share_location
    shareroute: share_route
    commandexecution: command_execution
    dataprocessortopic: abhaya

