server:
  port: 8099
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore.tomcat
    key-store-password: 123456789
    key-password: 123456789



# Postgres db configuration
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://111.93.16.246:5432/abhayadb
    username: abhaya
    password: abhaya
    testOnBorrow: true
    validationQuery: select 1 
    validationInterval: 30000
    maxActive: 120
    maxIdle: 120
    minIdle: 10
    initialSize: 0
    maxWait: 30000
    testOnReturn: false
    testWhileIdle: false
    removeAbandoned: false
    removeAbandonedTimeout: 60
    logAbandoned: false
  jpa:
    database_platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  data:
    elasticsearch:
      cluster-name: ES_Cluster_01
      cluster-nodes: 111.93.16.251:9300
      repositories:
        enabled: true
      
tcp:
  host: 
    name: 111.93.16.246
    port: 45567

kafka:
  bootstrap-servers: 111.93.16.246:9092
  group:
    groupId: abhya_app_group
  topic:
    deviation: deviation_topic
    distress: distress_topic
    video: video_topic
    routeintiation: route_intiation
    endtrip: end_trip
    sharelocation: share_location
    shareroute: share_route
    commandexecution: command_execution
    
route:
  url: https://abhayaotsi.epragathi.org:8099?