spring:
  profiles:
    active: local

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
    org.hibernate: INFO



jwt:
  header: Authorization
  secret: mySecret
  expiration: 120000
  route:
    authentication:
      path: auth
      refresh: refresh


sms:
  apiKey : 9VNpCj4ER+A-kBJuRsqUzpxkLo7LCHvHBhhSODAfhd
  sender : TXTLCL
  
route:
  url: http://111.93.16.251:8099?

rti:
  url : https://otsiqa.epragathi.org:9393/
  authKey : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiT1RTSSIsInBhc3N3b3JkIj
tcp:
  client: 
    port: 54678