
-- https://www.postgresql.org/docs/9.1/sql-createindex.html

--STATE INDEX
CREATE UNIQUE INDEX STATE_ID_X ON STATE (ID);

--DISTRICTS INDEX
CREATE UNIQUE INDEX DISTRICTS_ID_X ON DISTRICTS (ID);
CREATE INDEX STATE_DISTRICTS_ID_FK_X ON DISTRICTS (STATE_ID);

--CITI INDEX
CREATE UNIQUE INDEX CITY_ID_X ON CITY (ID);
CREATE INDEX STATE_CITY_ID_FK_X ON CITY (STATE_ID);
CREATE INDEX DISTRICTS_CITY_ID_FK_X ON CITY (DISTRICT_ID);

--OWNER_DETAILS INDEX
CREATE UNIQUE INDEX OWNER_DETAILS_ID_X ON OWNER_DETAILS (ID);

--VEHICLE_DETAILS INDEX
CREATE UNIQUE INDEX VEHICLE_DETAILS_ID_X ON VEHICLE_DETAILS (ID);
CREATE INDEX STATE_VEHICLE_DETAILS_ID_FK_X ON VEHICLE_DETAILS (STATE_ID);
CREATE INDEX DISTRICTS_VEHICLE_DETAILS_ID_FK_X ON VEHICLE_DETAILS (DISTRICT_ID);
CREATE INDEX CITY_VEHICLE_DETAILS_ID_FK_X ON VEHICLE_DETAILS (CITY_ID);
CREATE INDEX OWNER_VEHICLE_DETAILS_ID_FK_X ON VEHICLE_DETAILS (OWNER_ID);
CREATE INDEX SERIAL_NUMBER_X ON VEHICLE_DETAILS (SERIAL_NUMBER);
CREATE INDEX RC_NUMBER_X ON VEHICLE_DETAILS (RC_NUMBER);
CREATE INDEX VEHICLE_DEVICE_MAPPED_DATE_X ON VEHICLE_DETAILS (DEVICE_MAPPED_DATE);
CREATE INDEX VEHICLE_IS_DEVICE_MAPPED_X ON VEHICLE_DETAILS (IS_DEVICE_MAPPED);


--DRIVER_DETAILS INDEX
CREATE UNIQUE INDEX DRIVER_DETAILS_ID_X ON DRIVER_DETAILS (ID);
CREATE INDEX STATE_DRIVER_DETAILS_ID_FK_X ON DRIVER_DETAILS (STATE_ID);
CREATE INDEX DISTRICTS_DRIVER_DETAILS_ID_FK_X ON DRIVER_DETAILS (DISTRICT_ID);
CREATE INDEX CITY_DRIVER_DETAILS_ID_FK_X ON DRIVER_DETAILS (CITY_ID);
CREATE INDEX DRIVING_LICENCE_NUMBER_X ON DRIVER_DETAILS (DRIVING_LICENCE_NUMBER);
CREATE INDEX RF_ID_X ON DRIVER_DETAILS (RF_ID);

--DRIVER_DUTY_DETAILS INDEX
CREATE UNIQUE INDEX DRIVER_DUTY_DETAILS_ID_X ON DRIVER_DUTY_DETAILS (ID);
CREATE INDEX DRIVER_DETAILS_ID_FK_X ON DRIVER_DUTY_DETAILS (DRIVER_ID);
CREATE INDEX VEHICLE_DRIVER_DETAILS_ID_FK_X ON DRIVER_DUTY_DETAILS (VEHICLE_ID);

--CITIZEN_DETAILS INDEX
CREATE UNIQUE INDEX CITIZEN_DETAILS_ID_X ON CITIZEN_DETAILS (ID);

--EMERGENCY_CONTACT_NUMBERS INDEX
CREATE UNIQUE INDEX EMERGENCY_CONTACT_NUMBERS_ID_X ON EMERGENCY_CONTACT_NUMBERS (ID);
CREATE INDEX CITIZEN_EMERGENCY_CONTACT_ID_FK_X ON EMERGENCY_CONTACT_NUMBERS (CITIZEN_ID);

--TRIP_DETAILS INDEX
CREATE UNIQUE INDEX TRIP_DETAILS_ID_X ON TRIP_DETAILS (ID);
CREATE INDEX DRIVER_TRIP_DETAILS_ID_FK_X ON TRIP_DETAILS (DRIVER_ID);
CREATE INDEX VEHICLE_TRIP_DETAILS_ID_FK_X ON TRIP_DETAILS (VEHICLE_ID);
CREATE INDEX CITIZEN_TRIP_DETAILS_ID_FK_X ON TRIP_DETAILS (CITIZEN_ID);


--TRAVEL_TRACKING INDEX
CREATE UNIQUE INDEX TRAVEL_TRACKING_ID_X ON TRAVEL_TRACKING (ID);
CREATE INDEX TRIP_TRAVEL_DETAILS_ID_FK_X ON TRAVEL_TRACKING (TRIP_ID);
CREATE INDEX TRIP_TRAVEL_PACKET_TIME_X ON TRAVEL_TRACKING (PACKET_TIME);
CREATE INDEX TRIP_TRAVEL_PACKET_DATE_X ON TRAVEL_TRACKING (PACKET_DATE);
CREATE INDEX TRIP_TRAVEL_IMEI_NUMBER_X ON TRAVEL_TRACKING (IMEI_NUMBER);
CREATE INDEX TRIP_TRAVEL_SERIAL_NUMBER_X ON TRAVEL_TRACKING (SERIAL_NUMBER);



--ROUTE_DEVIATION INDEX
CREATE UNIQUE INDEX ROUTE_DEVIATION_ID_X ON ROUTE_DEVIATION (ID);
CREATE INDEX TRIP_ROUTE_DEVIATION_ID_FK_X ON ROUTE_DEVIATION (TRIP_ID);

--DISTRESS_DETAILS INDEX
CREATE UNIQUE INDEX DISTRESS_DETAILS_ID_X ON DISTRESS_DETAILS (ID);
CREATE INDEX TRIP_DISTRESS_DETAILS_ID_FK_X ON DISTRESS_DETAILS (TRIP_ID);

--WATCH_VEHICLE INDEX
CREATE UNIQUE INDEX WATCH_VEHICLE_ID_X ON WATCH_VEHICLE (ID);
CREATE INDEX VEHICLE_WATCH_VEHICLE_ID_FK_X ON WATCH_VEHICLE (VEHICLE_ID);


--STATUS_INFO INDEX
CREATE UNIQUE INDEX STATUS_INFO_ID_X ON STATUS_INFO (ID);
CREATE INDEX VEHICLE_STATUS_INFO_ID_FK_X ON STATUS_INFO (VEHICLE_ID);
CREATE INDEX DRIVER_STATUS_INFO_ID_FK_X ON STATUS_INFO (DRIVER_ID);
CREATE INDEX STATUS_INFO_SERIAL_NUMBER_X ON STATUS_INFO (SERIAL_NUMBER);
CREATE INDEX STATUS_INFO_RF_ID_X ON STATUS_INFO (RF_ID);

-- DEPARTMENT INDEX
CREATE UNIQUE INDEX DEPARTMENT_ID_X ON DEPARTMENTS (ID);


-- USER_DETAILS INDEX
CREATE UNIQUE INDEX USER_DETAILS_ID_X on USER_DETAILS (ID);
CREATE INDEX STATE_USER_DETAILS_ID_FK_X ON USER_DETAILS (STATE_ID);
CREATE INDEX DISTRICT_USER_DETAILS_ID_FK_X ON USER_DETAILS (DISTRICT_ID);
CREATE INDEX CITY_USER_DETAILS_ID_FK_X ON USER_DETAILS (CITY_ID);
CREATE INDEX DEPARTMENT_USER_DETAILS_ID_FK_X ON USER_DETAILS (DEPARTMENT_ID);
CREATE INDEX USER_NAME_X ON USER_DETAILS (USER_NAME);

-- RAW_PACKET_DATA INDEX
CREATE UNIQUE INDEX RAW_PACKET_DATA_ID_X on RAW_PACKET_DATA (ID);
CREATE INDEX RAW_PACKET_DATA_SERIAL_NUMBER_X ON RAW_PACKET_DATA (SERIAL_NUMBER);
CREATE INDEX RAW_PACKET_DATA_IMEI_NUMBER_X ON RAW_PACKET_DATA (IMEI_NUMBER);
CREATE INDEX RAW_PACKET_DATA_PACKET_DATE_X ON RAW_PACKET_DATA (PACKET_DATE);


-- DEVICE_COMMUNICATION INDEX
CREATE UNIQUE INDEX DEVICE_COMMUNICATION_ID_X on DEVICE_COMMUNICATION (ID);
CREATE INDEX DEVICE_COMMUNICATION_SERIAL_NUMBER_X ON DEVICE_COMMUNICATION (SERIAL_NUMBER);
CREATE INDEX DEVICE_COMMUNICATION_IMEI_NUMBER_X ON DEVICE_COMMUNICATION (IMEI_NUMBER);
CREATE INDEX DEVICE_COMMUNICATION_PACKET_DATE_X ON DEVICE_COMMUNICATION (PACKET_DATE);
CREATE INDEX DEVICE_COMMUNICATION_STATUS_X ON DEVICE_COMMUNICATION (STATUS);
CREATE INDEX DEVICE_COMMUNICATION_MOVEMENT_X ON DEVICE_COMMUNICATION (MOVEMENT);
CREATE INDEX DEVICE_COMMUNICATION_BATTERY_STATUS_X ON DEVICE_COMMUNICATION (BATTERY_STATUS);
CREATE INDEX DEVICE_COMMUNICATION_IGNITION_STATUS_X ON DEVICE_COMMUNICATION (IGNITION_STATUS);
CREATE INDEX DEVICE_COMMUNICATION_ENGINE_STATUS_X ON DEVICE_COMMUNICATION (ENGINE_STATUS);
CREATE INDEX DEVICE_COMMUNICATION_TAMPER_STATUS_X ON DEVICE_COMMUNICATION (TAMPER_STATUS);
CREATE INDEX DEVICE_COMMUNICATION_PANIC_BUTTON_STATUS_X ON DEVICE_COMMUNICATION (PANIC_BUTTON_STATUS);